### ISSUE TITLE
`ContextualVersionConflict` when following getting started instructions

### ISSUE THREAD

**Issue by mccalluc** [vitessce/vitessce-python#64]
I've followed the README instructions up to here:
```
git clone https://github.com/vitessce/vitessce-python.git
cd vitessce-python/
conda env create -f environment.yml
conda activate vitessce-jupyter-dev
pip install -e .
```
... and then I get this error:
<details>
<summary><code>pip._vendor.pkg_resources.ContextualVersionConflict: (pandas 0.25.1 (/opt/anaconda3/lib/python3.7/site-packages), Requirement.parse('pandas>=1.1.2'), {'vitessce'})</code></summary>

```
$ pip install -e .
Obtaining file:///Users/chuck/github/hubmap/vitessce-python
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 407, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pip._vendor.pkg_resources.ContextualVersionConflict: (pandas 0.25.1 (/opt/anaconda3/lib/python3.7/site-packages), Requirement.parse('pandas>=1.1.2'), {'vitessce'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 291, in _get_abstract_dist_for
    req, self.require_hashes, self.use_user_site, self.finder,
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 255, in prepare_editable_requirement
    req.check_if_exists(use_user_site)
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 418, in check_if_exists
    self.req.name
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pip._vendor.pkg_resources.ContextualVersionConflict: (pandas 0.25.1 (/opt/anaconda3/lib/python3.7/site-packages), Requirement.parse('pandas>=1.1.2'), {'vitessce'})
```

</details>

**Comment by keller-mark** [comment]
Can you provide your `pip` version? It looks like this may have been resolved recently based on this comment 14 days ago https://github.com/pypa/pip/issues/4537#issuecomment-839738231

**Comment by mccalluc** [comment]
```
$ pip --version
pip 19.2.3 from /opt/anaconda3/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by ilan-gold** [comment]
@mccalluc One thing that jumps out to me, and maybe @keller-mark can correct me since you seem to know `conda` better than me, is that you `pip` version is not localized to the environment.  For example all of your paths are something like `/opt/anaconda3/lib/` whereas when I have a conda environment, I get something like:
```bash
(bioformats) TecRef-LT-A0BC38:~ ilan_gold$ which pip
/usr/local/anaconda3/envs/bioformats/bin/pip
```

**Comment by keller-mark** [comment]
@mccalluc had the `vitessce-jupyter-dev` environment been activated in your shell before you ran `pip --version`?

**Comment by ilan-gold** [comment]
@keller-mark Even the logs initially posted seem to have the same issue.
