### ISSUE TITLE
`ValueError: "@jupyter-widgets/jupyterlab-manager" is not a valid extension`

### ISSUE THREAD

**Issue by mccalluc** [vitessce/vitessce-python#65]
Follow-up from #64 ... Continuing with the README, the next steps work, and then:
```
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager
An error occured.
ValueError: "@jupyter-widgets/jupyterlab-manager" is not a valid extension:
schemaDir is empty: "./schema"
See the log file for details:  /var/folders/2f/yvyq4r852yxg3xf902p52w5h0000gn/T/jupyterlab-debug-8qzkz0cf.log
```

<details><summary>debug log</summary>

```
$ cat /var/folders/2f/yvyq4r852yxg3xf902p52w5h0000gn/T/jupyterlab-debug-8qzkz0cf.log
Node v14.1.0

> /Users/chuck/.nvm/versions/node/v14.1.0/bin/npm pack @jupyter-widgets/jupyterlab-manager
npm notice
npm notice 📦  @jupyter-widgets/jupyterlab-manager@3.0.0
npm notice === Tarball Contents ===
npm notice 14.5kB LICENSE
npm notice 380B   lib/index.js
npm notice 15.3kB lib/manager.js
npm notice 5.3kB  lib/output.js
npm notice 7.8kB  lib/plugin.js
npm notice 3.3kB  lib/renderer.js
npm notice 862B   lib/semvercache.js
npm notice 3.3kB  package.json
npm notice 375B   schema/plugin.json
npm notice 2.8kB  README.md
npm notice 277B   lib/index.d.ts
npm notice 5.9kB  lib/manager.d.ts
npm notice 1.9kB  lib/output.d.ts
npm notice 828B   lib/plugin.d.ts
npm notice 960B   lib/renderer.d.ts
npm notice 216B   lib/semvercache.d.ts
npm notice === Tarball Details ===
npm notice name:          @jupyter-widgets/jupyterlab-manager
npm notice version:       3.0.0
npm notice filename:      jupyter-widgets-jupyterlab-manager-3.0.0.tgz
npm notice package size:  15.6 kB
npm notice unpacked size: 64.0 kB
npm notice shasum:        fa47d03e2e72399ce3af4b86cc29aba2166d5781
npm notice integrity:     sha512-9diAvsHHiK/kY[...]cKQSYU/tiXxdQ==
npm notice total files:   16
npm notice
jupyter-widgets-jupyterlab-manager-3.0.0.tgz

Traceback (most recent call last):

  File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 147, in run_task
    for i, arg in enumerate(self.extra_args)

  File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 147, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 321, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 525, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 1415, in _install_extension
    raise ValueError(msg % (extension, '\n'.join(messages)))

ValueError: "@jupyter-widgets/jupyterlab-manager" is not a valid extension:
schemaDir is empty: "./schema"

Exiting application: jupyter
```

</details>

**Comment by ilan-gold** [comment]
Maybe https://github.com/vitessce/vitessce-python/issues/64#issuecomment-853129837?

**Comment by keller-mark** [comment]
Should be fixed by https://github.com/vitessce/vitessce-python/pull/107
